# On Sensitivity

Sensitivity is required for art. Photographers and visual artists have a sensitivity to
light that is fundamental to their work. Rimbaud, that visionary poet, remarked
that a poet becomes a poet through a “systematic derangement of the senses”.
Making music requires sensitivity to how slight tweaks in a track affect the overall perception of the piece. Sensitivity is also required as
empathy; our profound empathy for others is what helps make our art universal
and for everyone.

Unfortunately, this profound sensitivity to the world also makes it difficult for artists to
live in the every day. 

My own sensitivity to sound and feelings make it difficult to ride the bus when
someone is loudly talking on the phone. I get drawn into conversations that I
don’t want to get drawn into; soon I’m feeling their tragedies or stresses and
as a result I arrive at work an emotional wreck. 

The real danger for sensitive artists in an unfeeling world is that it is often easy to
lose one’s sense of self when confronted with so many overwhelming experiences.
Such experiences are draining and tire us out and keep us from making art. Thus, it is important to know
how to protect oneself from these experiences. We can’t always be sensitive to
the world; otherwise we would be a bundle of raw nerves.</p><p>When they
are overwhelmed, artists and sensitive people have many strategies for escaping
these experiences. Some become emotionally withdrawn, reverting back to
childish and petulant behavior. Others seek alcohol and drugs to dull their
senses, or destructive impulses such as lashing out at others or destroying
property. 

There are less antisocial and less self-destructive ways to protect yourself when you are
overwhelmed. These include the following:

- *Mindfulness exercises and cognitive behaviorial therapy.* Both of these kinds of
therapies provide you with methods to distance yourself from the problem and
ask you why you are overwhelmed. Using these techniques can lessen the power of
the overwhelming situation.<br>
- *Isolating yourself from the problem behavior.*  This can be as simple as headphones, humming a song to one’s self, or going somewhere else. You must carve out such private spaces even in a public
space like a club or performance venue.
- *Realizing that your sensitive side needs to be protected much like a child.*  Don’t
ignore your own needs when you are feeling overwhelmed. Go somewhere else, calm
yourself down before you deal with anything else.

- *Cultivating a sense of humor can help*. Not only can it help defuse these overwhelming
situations, but it can lessen the impact. I doubt I would be alive today if it
were not for my sense of humor.

Obviously, these are just a few solutions to dealing with being oversensitive to situations, but I find they work for me. If you have any other solutions that you find helpful, I’d like to
hear it. The important thing is that you realize that you have nurture your
sensitive side for you to be at your best.<

## Resources

The two books I highly recommend are Elaine Aron’s <i>The Highly Sensitive Person</i> and Susan Cain’s <i>Quiet: The Power of Introverts.</i> Both of these books seek to recontextualize behaviors of
sensitive people that are often portrayed in a negative light. These behaviors
are presented in a way that showcase a sensitive person’s strengths, rather
than as weaknesses. I’ve found them extremely helpful as I find my way through the world.
