# On Craft

I think that most starting artists have an overly romantic view of craft. They buy into the cinematic notion that the conception and creation of an artistic work is a smooth process that proceeds like a feverish dream from the moment of inspiration in a single session. This makes for good film, but it's really not how the majority of artistic pieces are made.

The truth is that good works of art take a lot of work. Much of that work is good old fashioned problem solving. Many of us think that once we have the idea or the inspiration, the work is nearly done. But real creative work is dealing with unanticipated issues. For example, in translating a sketch of an outfit to an actual piece of clothing, there are tons of unanticipated problems, such as how two pieces of cloth must come together to fit correctly on a real person. Musically, we may have two themes we want to work together, but finding the chords or connecting melodies to do this requires a lot of experimentation. Writing a good story or a novel requires problem solving in executing a plot correctly, finding actions that are true to the characters and their motivations that execute the plot. A good poem is like a machine, with no word out of place and each word contributing to the effect of the whole poem. Executing each of these art forms well requires creative problem solving.

I propose that you divide creating art into three distinct activities: 1) *capturing inspiration*, 2) *working/problem solving*, and 3) *editing*. The majority of your work will be working and editing. Note that working and editing must be distinct processes. When you work, you must be free and uninhibited; when you edit, you must be merciless in what you cut and what you include. If you do the two together, you will end up being creatively paralyzed.

## Capturing Inspiration

First of all, toss that notion of working on a piece in a single feverish session away. You live in the real world, and barring having a wealthy sponsor, working like that is a luxury most of us don't have. You need to be able to capture your inspiration when it comes, as it often does at inopportune moments, such as the shower, on a walk, or during work. Lots of tools exist for capturing these moments of inspiration, such as notepads, recording apps, and cameras. You should get over any feelings of awkwardness or self-consciousness when using them in public.

Your capture tools should be fast, simple, accessible, and adequate enough to capture your ideas accurately. Transfer your ideas to some sort of long-term storage. Store your ideas in a notebook, a file folder of hummed recordings on your desktop, or an photo album of beautiful pictures. The point is to be able to rapidly review ideas for follow up. Be sure to eventually act on your inspiration. Otherwise, those ideas lie fallow, much like rolls of exposed but undeveloped film. It's wasted potential if you don't act on your ideas, and your muse will be displeased. You may find your wellspring of ideas may dry up because you failed to act on them.

You may find it useful to dispose of ideas that have sat in long-term storage for too long. These unworked ideas can weigh you down creatively and should be let go. Occasionally revisiting and clearing out your backlog is essential to the creative process.

## The Work

The next step is working, the creative problem solving. You act on that inspiration that you've captured, when you have the proper time to work at it. You must be willing to do the work. There are no shortcuts. You must learn what works and what doesn't in the context of your piece. You must not be precious about the work. Working only when you are "inspired" is a specious notion. The most important thing is to start and maintain momentum. Studying theory (music theory, color theory) and art history can help you understand what solutions to similar problems others have used. But your solutions must be practical and personalized to your vision. Don't be afraid of making mistakes. Digital tools give you the freedom to go back if we make a mistake. Make multiple versions if you are unsure.

Working is far from a linear process. I rarely work from the start of a piece to the end of it in a linear fashion. My own musical process tends to be to create tons of versions of a musical phrase and then figure out how to connect them together. I need to have a seed idea, which can be a tiny repeated sample or theme to work on. When I write, I often put all of my ideas on the page at once, using a mindmap. Seeing all the ideas on the page at once helps me discover the structure of the piece I write and allows for happy accidents to shape the piece.

You should work without feeling self conscious and critical. Save being critical for later when you have had the proper time to see the shape of the work. You can always go back and fix things later.

A note about those who improvise to produce their pieces. This is a unique process unto itself, and it's easy to generate a lot of material using this process. If you have the improvisational skills, it's relatively easy to hit record. Where I have seen many an improvisational musician fall down is in the editing stage. Due to the ephemeral nature of performance, what works live does not necessarily work in the recorded setting, where the listener can endlessly relisten to something (I find many live recordings to be tedious because of this). Selecting the moments of improv that work and stitching them together can be a difficult process, and it can take much longer than the actual improv. When Marcus Fischer and I put together *Tessellations*, the base of it was improvised, but then we had to mercilessly edit 20 minute sessions into coherent songs. 

## Editing

When you have done some work, then you are ready to edit. Make sure to separate editing from working, otherwise it will paralyze your working process. It is often good to give yourself some time between working and editing. You can edit the work with a fresh perspective and with less emotional attachment to ideas.

During editing, you must understand how each individual idea contributes to the piece as a whole. Be merciless and don't get emotionally attached to any one idea. If an idea works, keep it; if not, save the idea in another file of other ideas to pursue later. If it's a good idea, it will eventually find its place. If not, just know that the creative road to every standup routine, novel, and symphony is littered with lots of discarded ideas. Look at Beethoven's drafts; he discarded huge sections of pieces from draft to draft, and crossed out whole pages the manuscript. I personally find it comforting that all artists struggle. The ones who say they don't are probably lying.

The act of editing can be creatively cathartic in itself. Often, it's only by discarding ideas that I can see the true shape of the work. Once you have a vision of the form your work is supposed to take, the process will become easier. You will become more sure of whether an idea belongs or not as you continue.

Oftentimes, the editing process generates new ideas, which may be useful to the work or external to the work. Be sure to capture these and use them in the next working phase.

## The Thick of It

You will often iterate between working and editing. They take two different states of mind, so it is often useful to schedule a working period with one or the other in mind, based on your current mindset. When you're in the thick of it, it can often seem like an endless process. Fight the feelings of inferiority that arise. Persist, and you'll see it through.

Hopefully, through this process, you will discover the structure, or form, that suits your piece best. Do not dismiss finding the proper form; it's the architecture and the scaffolding that you hang your ideas on. A good form can be the difference between someone being indifferent to your piece or making a deep and lasting connection. Think of a good pop song; it gets to the point and it does it in a structure that can still surprise us to the day. Presentation is important.

When is a piece done? When viewed externally, other artists' work might seem to have an air of seeming inevitability to it. In interviews, these artists often play up this sense of inevitability, suggesting they are merely tools of fate. This is mostly hogwash. A work of art is really only finished in the mind of its audience. Mark Snow, in an interview with Kumail Naijani, remarked at the indifference Chris Carter and the TV executives had to the X-Files theme before the series aired; it was only after the show aired and the audience liked it that they acknowledged it as a masterpiece. One of my most used pieces, "Silhouettes", was originally twice its length; it was only after I had to fit it into a time requirement that the "right" length emerged. My point is to realize that the endless tinkering has to end at some point.

However, you should feel good about the work for it to feel finished. If you don't feel it's done, then it probably isn't. There will always be nagging doubts about your work; if you are worried, release your work in a safe forum, send it to artistic friends you trust first. It's often great to get the perspective of an artist outside your field; they will talk about it in artistic language, but unhindered by the perspective of your field. Make sure to extend this courtesy to them when they ask for it as well.

## Having a Process to Creatively Enable You

I realize that most of you at this point are probably dismissing me for taking the romance out of the creative process. These thoughts about process and craft are hard won after years of creatively floundering about. I realized that the way I worked was counter productive, and wasn't any more fun. By separating working and editing, my process has become way more fun and less dramatic. Starting a work has become an exploration of possibilities rather than one burdened with unreasonable expectations. I give myself permission to utilize happy accidents and to abandon projects that don't inspire me.

The point really is to start, not to regret that you never did any writing, composing, or painting late in life. Artists with staying power find that the work itself is incredibly rewarding; everything else is really icing on the cake.

## Resources

This piece is the distillation of my own personal experience and observing the creative processes of others. As a corrective to the cinematic notion of craft, here are some good movies about the work involved in the creative process. 

[The Kingdom of Dreams and Madness](http://m.imdb.com/title/tt3204392/) about Hayao Miyazaki and Studio Ghibli is a powerful meditation on a master of animation and how he works. I thought it especially interesting in light of how his studio has adapted to his process.

[Crumb](http://m.imdb.com/title/tt0109508/), about the work of R. Crumb, was a big influence in getting me to understand how important working is to creativity. 

[Touch the Sound](http://m.imdb.com/title/tt0424509/), about deaf percussionist Evelyn Glennie, is a profound look at being inspired by the world and her creative process. There is a great moment in the movie where she and Fred Frith are banging on pipes in a warehouse where she is recording.

[Topsy-Turvy](http://m.imdb.com/title/tt0151568/) is a wonderful view of the amount of work it takes to mount a musical (Gilbert and Sullivan's *Mikado*) from conception to the stage.
