# On Recharging

You are not a factory. If you are commercially successful, the treadmill of commercialism may demand you churn work after work, piece after piece. But tailoring your work to the external world comes at the cost of diminishing your internal world. Creating art is not manufacturing. It is not a commodity, it is a gift to the world. There is a tricky balance in commodititzing your work and letting the work remain true to itself. I've seen many successful artists burn out because they were not able to say no to the flood of commercial expectations and job offers. These artists burn out because they don't take the time to recharge their creative batteries. New ideas don't come because they have become complacent and they have not appreciated the source of their creativity.

How do you recharge? First, get off the treadmill. Schedule time to recharge. You should view recharging as a necessary part of your work. It may be difficult to justify to yourself, but think of it as an insurance policy for your creativity. If you don't protect your creativity, no one else will.

In order to recharge, there are many activities you can do to jar yourself out of creative complacency.  Here are a few I've found to be good. I'll talk about each in turn.

* Revisiting works that inspired you previously.
* Walking or interacting with the natural world.
* Trying something new or putting yourself in a new mental space.
* Working in a different art form.
* Mindfulness training and meditation.
* Avoiding social media.
* Being less hard on yourself.

Revisit your creative source and honor your muse. Sometimes this means revisiting the distant past. I think about re-listening to albums that I was obsessed with when I was younger and try to approach these albums with fresh ears. Why was I obsessed with them? I draw energy from remembering my old enthusiasms. 

I draw energy from walking in nature. I am always inspired by the infinite variability and adaptability of life, of how plants grow and develop. The forms of nature are always energizing and inspiring to me. Lying in a hammock, watching the leaves tremble in the wind as I sway back and forth, creating delicate rhythms and textures that I find inspriring. Bird calls embed themselves into my subconscious.

I also recharge by trying new things, and listening to new music. I love hearing music from different parts of the world, from Javanese Gamelan, to Scandanavian drone metal, to Ethiopian Rock. Trying new things puts you in a different frame of mind and lets you see things anew. Pay attention to your feelings when you try new things. Are you uncomfortable? Are you energized? Harness those feelings, remember them. I think that feeling of discomfort and uncertainty is important to creating new art. When I start getting reductive about my music, I am in a bad space with it. 

Go to shows, support others in art. You never know when you will be inspired by other people's work. Sometimes the act of connecting with new people can be energizing. Listen to new music with friends, and talk about it. What worked and what didn't work? Can you build on that? Does your dislike of a piece spur you on to do better?

Try mindfulness training, such as meditation. Again, the goal is to see things differently than your current viewpoint. Maybe you've been beating yourself up over a failed project to the point that it's impeding your current work. Mindfulness training can help you step outside of yourself and gain clarity on issues.

If you have commercialized one of your art forms, it can be sometimes difficult to deal with the crushing weight of audience expectations. I have found it useful to have another parallel art form (in my case, photography)  that I do for myself. A surprising number of actors are also painters. I draw energy from rediscovering the beauty of the world through my photography. My photographs serve as reminders to myself that there is beauty in the world if I dig deep enough.

Part of recharging is unplugging from things that emotionally drain you, especially social networks. When I am burned out, I find social networks emotionally and creatively draining. Everyone's endless updates make their lives seem much better than mine, and it drags me down into a depressive hole. If you feel this way, you should unplug (thanks to Tim Gray for this suggestion) and focus on real life interactions. When you feel worthless is when you most need to interact with real life people. Being with people reminds you that everyone is not perfect, and that everyone struggles.

It's also worth reminding you not to be too self critical or harsh on yourself if you do not meet your own (possibly unrealistic) expectations.  Beating yourself up might be an ok short term strategy, but we are playing the long game. The desire for perfectionism can be the worst creative block of all. 

So, in conclusion, to creatively recharge you need to jar yourself out of complacency and go where you are uncomfortable. You need a new concept and perspective of what your art can be and how it fits into the rest of the artistic world. You need to revisit your creative source and honor it.

## Resources

[*The Gift*](http://www.lewishyde.com/publications/the-gift) by Lewis Hyde is a great read and a reminder of why we make art. Making art is making a gift to the world, and it's ultimately more important that you gave the gift to the world rather than how it's received.

[*How to Really Relax*](http://lifehacker.com/how-you-can-learn-to-finally-really-relax-1548045887) is a nice reminder of things you can do to recover from burnout.