# On Depression

I have a depressive personality. When I am depressed, my brain actively works against me. I have feelings of worthlessness and I doubt myself. I obsess and ruminate about the few bad things that happened that day, way out of proportion to their effects. I play the comparison game, comparing myself to others. I always lose the comparison game. 

I have found cognitive behaviorial therapy (CBT) to be one of the few really effective treatments for my depression. I've gotten much better at self-soothing, comforting myself when I am in a depressive downwards spiral. I have a lot of self-defeating patterns that I fall into, and which have their own terrible power over me. I ruminate and brood, which makes me feel like I am inferior to other people and makes me overinterpret the thoughtlessness of others way too personally. (In fact, I think you could call me *the boy who took things too personally*.) CBT has helped me dispel the power these patterns have had over me. I am, in fact, as good as everyone around me. I now choose to be bemused rather than openly irritated at thoughtless behavior. I feel like my agitation and anxiety have lessened to the point where I feel less overwhelmed.

CBT has forced me to re-evaluate what I consider the worst case. For example, what is the worst thing that would happen to me if my bag broke open on the sidewalk? One of my big triggers is when I feel I am being ignored, which can lead to self-destructive and alienating behaviors. It's during these times when I have the overwhelming feeling that "everyone is a jerk" - something I still struggle with. But I now know that it is a perception in the moment and not the actual reality.

The rumination can be the worst part of depression for me. I can get stuck in endlessly replaying awkward social interactions and beating myself up for it. This rumination can make me feel like I'm worthless, my art is worthless, and *no one wants to hang with me*. I get caught up in the thoughts that I am not reaching the goals I set out for myself. What helps me stop this endless cycle is mindfulness and meditation; it helps me get out of myself and this thought process. The art itself can also be therapeutic and cathartic, but only if I let go of my expectations about it.  I've also learned to be less harsh on myself. I may get less done than I'd like to, but I'm also more mentally healthy.

CBT has also helped me recontextualize what I originally thought of limitations. I used to think I was a total introvert, which to me meant that I wasn't good at interacting with others. To the contrary, I am quite good at interacting with people when I have a role, such as teacher or mentor. I know what to say to put people at ease. People tend to interpret my lower energy state as authoritative and calming, which makes my own nature work for me, rather than against me.  I've always had grace under fire, and I handle stressful situations external to me better than others, and that is partly due to my depression. Teaching helps me and energizes me.

After all these years, I feel like I finally understand Michael Caine's advice to "[use the disadvantage](https://books.google.com/books?id=ES6ZAAAAQBAJ&pg=PT91&lpg=PT91&dq=use+the+disadvantage+caine&source=bl&ots=0NxeOR-4iO&sig=XsFL4clh_687Cr3UN-nZZ_s_bIs&hl=en&sa=X&ei=9XhwVcb-H8nZoATFwoOABA&ved=0CCAQ6AEwAA#v=onepage&q=use%20the%20disadvantage%20caine&f=false)". That is, use what people view as flaws to your advantage. I used to criticize myself for not being more extroverted and outgoing. I have instead learned to use my own curiosity and empathy for others to connect with them at my own comfort level. I used to be anxious about embarrassing myself, and be anxious about saying the "wrong thing". I've learned since that making mistakes is human, and can actually connect you to other people. I used to think my software and music had to be perfect before I released it. I've since learned to release early and welcome feedback. My sensitivity, which I often considered a weakness, is actually one of my greatest strengths. I am a good analyst because I am data sensitive, sensitive to patterns in data. Likewise, such sensitivity is part of [what  makes me an artist]({{< relref "2015-05-09-on-sensitivity.md" >}}).

These judgements about myself did not come from nowhere - they are derived from reactions of others to me that I wrongly internalized - and I would plead to those who are more neurotypical to not spread judgements of others based on an initial reaction of depressive people. Seeing people grow up in the age of social media worries me. Words can hurt when you are sensitive and depressed. Think about that the next time you get outraged or are feeling snarky. 

Believe it or not, there is also a positive side to my rumination - if I focus it on the right things and don't get obsessive. I process feedback and learn from my mistakes. I show dramatic and rapid improvement in learning new skills because of this. I just try not to focus on details that are in the past and which I cannot fix. That can be an uphill battle.

In conclusion, my depression is part of me whether I like it or not. I finally feel that I work with it now rather than against it. It has been a very slow process of reducing my expectations of myself and accepting my true strengths. I refuse to believe that good art comes from personal drama; I think it really comes from curiosity and compassion. I hope that this essay helps someone struggling with similar thoughts.

## Resources

The most important step if you are depressed is to seek help. You will need to unpack your emotional baggage in order to unburden yourself, and that is best done with a therapist. [The Anxiety and Depression Association of America](http://www.adaa.org/finding-help) is a good place to start. Keep in mind that CBT doesn't work for everyone and treatment can be an uphill battle. A newer type of therapy, Dialectical Behavior Therapy (DBT), may be a better fit for you. Medication may be an important part of your treatment plan - and finding the ones that work can be a long process of trial and error.

Lars von Trier's *[Melancholia](http://m.imdb.com/title/tt1527186/)* is an important movie for me in that it helped realize that there is grace in depression, and that depression can carry a quiet authority. Neurotypicals are not equipped to handle crises as well as depressed people.

Every couple of years I revisit Woody Allen's *[Another Woman](http://m.imdb.com/title/tt0094663)*, a quietly devastating movie about unpacking your demons. I love Gena Rowlands as a philosophy professor whose self deception can only take her so far. Soon enough, regrets and repressed feelings must be given their due.
