# On Success (or, How to suck it up and be happy for your successful friends.)

It can be egotistically bruising when one of our friends is successful and by comparison, we are not. But you should be happy for your friends when they are successful for the following reasons. I'll talk about each in turn.

* *Success in the art world is rare, ephemeral, and should be celebrated.*
* *Their success is partially due to you and your artistic community.*
* *Bitterness destroys no one but you*.
* *Comparing yourself to others is a losing game.*

The world itself is hostile, or at best, indifferent to art. As artists, we need scenes to support us and our visions when the rest of the world does not. There are countless scenes that are examples of this: I think of the Beats, the Bloomsbury group, the shoegazers, the NY Downtown scene that gave rise to Talking Heads, Patti Smith, and Television. Artists in each of these groups supported each other, helped each other, attended each other's events despite their widely disparate visions of art. Such creative relationships can energize the work, as David Bryne talks about in his chapter on CBGB, ["How to Make a Scene"](http://loud-time.blogspot.com/2012/12/this-aint-no-memoir-how-to-make-scene.html?m=1). 

Success itself in the art world is rare and should be celebrated. I believe that we as artists should shed the notion of competing with each other and instead encourage each other to grow and develop. Artistic competition is an illusion perpetuated by the capitalist market and the small pot of grant and foundation money that exists for artists. When the success of an artist is the product of a scene, that success belongs to the whole scene. Success itself may be ephemeral, but a musical community is not. 

Success is partly the product of hard work and partly the product of uncontrollable forces, which most people call luck. I prefer to think of it as an alignment of broad cultural priorities with the work of the artist. Most artists, though they work hard and have good promotion, fail to 'make it' - that is, fail to have their work recognized by a larger audience. For a select few, their work will resonate with a larger audience, but it seems like the duration of this resonance is getting shorter and shorter. Momus, the clever quipper that he is, riffed on Andy Wharhol's statement that "everyone will be famous for 15 minutes", instead asserting that "everyone will be famous for 15 people".  

You should also be happy for the successes of others because it's better than the alternative, which is being bitter. I think bitterness is the enemy of art. I think we all know someone whose bitterness has partially ruined their life, and that has tainted the lives of those surround them. Bitterness ruins relationships and leads to loneliness. I would rather have the support of close artist friends than the vague support of a larger audience.

It's equally important to manage expectations. Unrealistic expectations can doom us to feelings of failure, especially when those expectations arise from comparing ourselves to the success of others. Don't compare yourself to others and beat yourself up. This is the way of bitterness. Complaining that you don't have the recognition you "deserve" will only gain you a reputation as a complainer. It's better to find your own path if the current paths aren't working for you. Countless artists have struck out on their own when the current art world had nothing to offer them. It can be a hard, but  rewarding path if you take it.

It took me a long time to realize that external validation is largely useless to me. What should matter most is that you feel good about releasing the work into the world, that you executed it the best of your abilities, and made compromises that you can live with. Integrity is what matters the most to me.

For those who are successful in this moment, I would remind you of what Joan Rivers says in an episode of Louie: remember the people who helped you on the way up, because you'll need them when you're on the way down. Likewise, entitled musicians who think they deserve deluxe treatment and treat everyone else badly probably aren't going to be tolerated for long. Those who define their success by the number people they think they can treat badly are doomed to be alone.

So, in summary, success can be fleeting and is not usually created in a vacuum, it's usually a product of an artistic community. In this context, we should celebrate the success of our friends. We should also avoid comparing ourselves to others and becoming bitter as a result. To do so is to practice gratitude for your audience and to cement your position in a musical community. Given that success is not handed to all of us, I am very happy with community and friends as a consolation prize.
