# On Artistic Influences

It's often said that "good artists borrow, but that great artists steal." Stealing is a necessary process to making art, but I think it only works when you have a thought process behind it. What you steal should be processed by you such that the influence is unrecognizable on immediate listens. It's not enough to reference an era; you have to make that era yours. Otherwise, you are simply beholden to the past and are contributing nothing new to the world.

By all means, you should consume and be inspired by other people's art, but you must destroy them and surpass them as well. Killing your idols is necessary to progress as an original artist. In order to progress, you must develop your own aesthetic. An aesthetic is not a brand; an aesthetic is a way of perceiving and interpreting the world. It is constantly mutating in response to the world, but always has a core.

What is an aesthetic? One definition is that an aesthetic is "a set of principles underlying and guiding the work of a particular artist or artistic movement." Your own aesthetic must be deep, or it will not sustain you. I've seen many artists who believe their 'sound' or personal stamp is derived from a single technique, such as a single effect plugin, or a color palette. Relying on a single tool or influence to shape your art is unwise. You must have a creative process that is external to your tools, or your tools will determine your creative process. Without an external process, you will reach creative dead ends. Developing this process is part of discovering your own aesthetic, and discovering it can be a tortuous process. But it can also incredibly fun and never ending.

An aesthetic is not a brand. A brand exists to give identity to merchandise, and an aesthetic is much more than that. It's your through line that when understood, will unify your body of work. It defines what your work is, but also what it isn't. It should reflect your enjoyment, but also your frustrations with current artists.

You should protect your aesthetic, as it's what makes your work unique. If you are lucky enough to inspire copycats, you must go beyond them into realms where they would not dare. People may copy your surface style, but they can't copy your aesthetic if it is a deep one. If you can, it's probably better off not talking about it in public. I think it's better for people to discover it for themselves. I think about how mysterious those Boards of Canada records were when they first came out. Everything about them was a fascinating mystery, from the voices, to the song titles, to the 70's warbly synth soundtrack feel.

Get good at taking works you admire apart. Understand why a particular musical moment is powerful and moving. Is it because they broke an established pattern? How did the artist overwhelm you and subvert your expectations? Was it a shock, or was it a more pleasant surprise? How did they do that? These details are all grist for the creative mill.

It's always interesting to find out about what techniques an artist used to get a particular effect or sound, but I usually find that obsessively collecting gear to reproduce a particular sound is counterproductive. It's a scavenger hunt whose results are always mildly disappointing to everyone. Even if I had every bit of Kevin Shields' gear, I doubt I would sound like him. Thinking about his technical limitations and how he overcame them is much more inspirational to me. Thinking about the creative principles behind a work is inspiring as well. I use a lot of detuning in my work, inspired by My Bloody Valentine, but it's manifested as cello overdubs rather than trying to recreate it with detuned guitars. Find the higher order principles that make a piece work and you can make them your own.

There is nothing new under the sun. Most creative techniques have been used at one point or other, but they haven't been used by you. What ultimately makes a creative work unique is you - and your mix of influences and artistic ambitions. Cultivating your own unique aesthetic is an important part of the artistic journey and will serve you in good stead.

## Resources

[How to be creative](http://gapingvoid.com/2004/10/18/how-to-be-creative-in-pdf-format/). Early on, I found these principles very helpful, since they are focused on making your work unique.

[Myths about creativity](http://lifehacker.com/demystifying-the-muse-five-creativity-myths-you-should-1688503554) this was a nice little article about busting some untrue myths about creativity.
