# On [Musical] Collaboration

I love to collaborate. One of the reasons I enjoy playing the cello so much is that it can play many musical roles: lead, rhythm, backup, counterpoint. Having the cello as my instrument forces me to be versatile, and to find my sonic niche in every collaboration I participate in. However, not all collaborations turn out well; some fizzle after the first piece we work on. Usually after the first piece we work on I will know whether my partner is a good collaborator for me.

For me, a good collaborator is open to new ideas. They are believers in the ["yes, and..."](https://en.m.wikipedia.org/wiki/%22Yes,_And%22_rule) school of improv, building upon your work rather than tearing it down. Collaboration requires a fundamental level of trust, and getting to this point of trust is not easy. A lot of people seem to think that collaboration is a competition, wanting to stand out from others they work with. I find these kinds of collaborations to be shallow and draining.

For me, the best collaborations enable us to jointly venture into unknown and uncertain territories. My collaborator and I may not know the boundaries of what we do, but we are open to exploring. We may start with a simple idea, or with improvisation. But our goal is that we discover the form and structure of the piece together. We edit together, bounce ideas off of each other, and decide when a piece is finished together. We make mistakes together, and may find that our best ideas arise from these mistakes. We make a safe space for each other to be musically vulnerable. Only when that respect is there can the true music making begin.

Part of being a good collaborator is making a safe space for your collaborators to try new ideas. Make it safe to make mistakes together, since it is often the mistakes that become the foundation for something interesting. If you are dismissive of my ideas or grab the keyboard every time I try something, that is not making a safe space. Communication is key. Make any criticisms constructive rather than destructive. But be honest.

All artists have big egos, but we must set them aside when we collaborate. We cannot be threatened when our collaborator plays better than us (our collaborator may have to realize that he is grandstanding). We cannot rewrite or rerecord our collaborator's parts, as much as we would like to. We must be willing to give up a measure of control in the collaboration.

By giving up control, we give the collaboration room to breathe, develop, and grow. We may find our collaboration sounds completely unlike our separate work, but only if we are open to this possibility. You don't have veto power over your collaborator's contributions, nor they over you. Yes, that may not be the way you would have executed a part. But that's why you collaborate, to get out of your head and to work with ideas which aren't your own. Some people are so in their own heads that their own aesthetic and ideas don't play well with others. You must always be aware of overdominating the musical conversation. If you are inflexible over a piece, you need to let that go.

I am far from an ideal collaborator, but I attempt to give my collaborators their space. I make sure there is space for me to react to their contribution and vice versa. Many times, it takes a lot of experimentation and improvisation to discover the form of the music together. Often, the first moments of an improvisation are uncertain. New ideas and combinations are tried, and they often fail. Discovering the common scales and modes between you can be difficult, if such things are usually not discussed beforehand. The improv and its development is much like walking a tightrope.

All of these interactions become more complicated when more people are added to the collaboration. A two person collaboration is mostly a conversation, whereas a three person collaboration can become an uneven power struggle, a la Sartre's *No Exit*, a work that posits that "hell is other people". The minority opinion in these cases must be respected, and not dismissed. Again, it's not a competition of ideas. Respectful discussion is encouraged; don't look at any decision as a mutually exclusive one. Often, compromise can lead to a new path being discovered.

Lastly, part of the secret to a good collaboration is saying no to the wrong collaborators. Seriously, don't work with jerks, no matter what they promise. A jerk, by my definition, is more interested in the outcome than the process.

A collaboration can be a wonderful side road to explore, producing new and unexpected work, and it can be a necessary creative jolt. But a true openness of spirit is required to make it work. Disregarding personal dynamics and feelings in collaboration leads to poor work, and is often at the root of many band breakups. However, if you lose the ego, you may find a brand new source of creativity.

**Resources**

* Read Aristotle's chapter in the *Nicomachean Ethics* on virtuous friendship for [inspiration on how to be a good collaborator](http://cantory.blogspot.com/2007/12/aristotle-and-his-view-of-friendship.html).
* [*High Status Characters*](http://www.goodreads.com/book/show/18050769-high-status-characters), the oral biography of the Upright Citizens Brigade, has an excellent chapter on the "Yes, and..." school of long-form improvisation. The rules are useful musically as well.
* [Rules for creative collaboration](http://openendedgroup.com/images/CreativeCollaboration_OpenEndedGroup.pdf) is another formulation of these rules for collaboration. I don't particularly agree with all of them (I disagree about their feelings about compromise), but as an additional perspective, it's useful.
