# On Listening

> Note: I was asked by Steve Ashby, who teaches a music appreciation class at Virginia Commonwealth, to contribute my thoughts on listening to music as part of his series ["Listeners on Listening"](http://rampages.us/mhis243/listeners-on-listening/ted-laderas/).  I've reproduced the interview below.

*You buy a new album, or hear a new piece for the first time, describe your routine/experience of its first listening.*

On first listen, I hope to be captivated and swept away, so I don't pay attention to details. I listen with my heart, and not my mind. I focus on moments in the music, where the music changes dramatically and it sweeps me with it. If I'm lucky, I might gain some knowledge of the structure, or form, and understand how it supports these moments.

*On subsequent listens to that same record/piece, which aspects of the music do you focus your listening on. How does your listening perspective change over time?*

I try to keep my listening on a largely uncritical level. Listening truly critically can hamper my enjoyment of a piece. It's only later when I want to know how a piece works that I start to listen to it critically. Even then, it's impossible for me to completely take a piece apart. I tend to focus on single parts and how they contribute to the texture of the piece. How does the mix emphasize the melody or the harmony? How does the composer handle the transitions into those sublime moments? If I'm receptive enough, I can learn all of this and apply these concepts to my own work.

*If you could choose your favorite listening environment, what would it be? what draws you to that place to hear the music you’re listening too?*

It really depends on what kind of music I am listening to. One of my favorite listening experiences ever was seeing Tim Hecker as part of Rafael Irrizari's *Substrata* Festival series. The music was overwhelming and the bass hit me in the guts. It was an incredible listening experience where I got swept up into the tidal wave of sound. I've only had that kind of visceral listening experience a few times, but they were magical moments.

Otherwise, I just love listening to music on headphones while I am doing nothing, preferably lying down. There's something about lying in a hammock, slowly swaying in the wind, watching clouds drift by while you are listening to music. Your brain expands and you get lost in the sonic world of the piece.

 4. *How does one make their listening listened to? What is the best avenue to communicate your listening experience to others?*

I think it is probably best to lead by example in terms of listening. I do love that listening parties are a thing nowadays. I think it's great that listeners can have a shared experience of listening to a brand-new recording.

As for sharing that experience, there are only a few people who I really feel comfortable sharing my private listening experiences with. These are people who know my tastes and I know theirs, so there is already common ground. There are countless ways to share music, but really only a few ways to share listening experiences with each other.

We must never forget that one of the functions of music is a social one. Before Beethoven, concert goers frequently talked throughout the concert! The notion of a rapt audience is a fairly new one in the history of music. Music in bars serves a different purpose than music in concerts, or at listening parties.  People go to bars to forget about life, to commiserate, to hook up. So anything that doesn't fit in these categories is going to have difficulty being accepted at a bar.

*How does your focused listening to music help you hear the world around you? How does it build awareness to the sounds in your everyday life?*

I am overly sensitive to the world - it is easy for me to get drawn into an overheard conversation on the bus or elsewhere. In loud social situations, I sometimes have to tune everyone out. Everyone seems so desperate to stand out in the world, and it can be an intolerable cacophony for me. Daily life can be painful without tuning it out. I have to find ways to dull this sensitivity.

Being in nature when I am sound sensitive is pleasurable in contrast. The rustle of leaves, creaking trees, the caw of crows, the sound of rushing water are very vivid to me.  Going outside is my way of refreshing my ears, especially when I am in the midst of doing detailed musical work such as mixing.

*Do you feel you listen to music differently as an audience member vs. a performer? how so?*

Listening as a performer is very different than as an audience member. I incorporate a lot of looping and improvisation when I perform, so I must react to what I have layered before. When performing, I listen to understand which direction I want to take a piece in. I have to be open to the possibilities and I must give myself room to add to the looped performance. I often hear what I'm going to do in my head before I perform it.

When improvising with others, I listen for the holes in my band mates' performances to find my niche. The worst improvisers are the ones who don't listen. They steamroll over their bandmates' performances and are selfish with the spotlight. Improvising is not only about what notes you play, it's also about what notes you *don't* play and how your part contributes to the whole gestalt. To play too many notes when you improvise is a sign of insecurity.