# Undeveloped Film, or the Tyranny of Unfinished Work

Among other things, I am an avid photographer. I used to do a lot of black and white photography. I loved processing and printing my photos in the darkroom. One of the worst times in terms of my creativity happened because I lost access to a darkroom. I was shooting a lot of film, but then never developed it. This undeveloped film started weighing on me heavily, and not seeing it finished took a toll on my creativity.

I have to say that not developing this film made me feel the worst about myself and my art that I've ever felt. It's only now that I really understand why this was so.

Unfinished work is a mental burden and its presence can hinder your creativity. I know that an artistic work is rarely definitively finished, and [some say it is only abandoned](https://quoteinvestigator.com/2019/03/01/abandon/). Nevertheless, you must try to seek closure, even if that closure is somewhat unsatisifactory. Otherwise, the promise of these unfinished works takes up precious room in your creative capacity and memory.

When I’m composing, a looped bar of music can quickly become fixed in my mind and fail to become a song. In some respects, it can become a prison of my own making. Better to blow it up, make lots of versions of it very fast so it doesn't become fixed, and retrospectively make sense of it and discover how these multiple versions work together.

## Don't be precious about your art

We fix creative ideas in our minds because we feel like they are precious, unrenewable resources and that to alter them would ruin them. 

So, to get unstuck, we have to give up this preciousness. We must respect the idea, but not be bound to it.  We have to disrespect it and not be precious about it. If we can maintain this balance, we will realize that creative ideas are indeed a renewable resource.

The only constant to art is that the rules are not fixed. Becoming fixated on what something *should be* leads to being creatively stuck. Most of us will not conceive an art piece in full from the beginning. We have to be open to the journey of discovery and understand where that germ of an idea can take us. We need to explore the space of possibilities that germ can provide.

## Free your RAM

I have a folder full of unfinished pieces. At some point, I will have to just not finish these pieces because they are weights on my creative brain.

Your creative brain has limited RAM. If you’re fixated on the failures, and whether or not what you work on is going to be a failure, you leave little room for being creative. 

What I do is that occasionally I will cull the list of things I am working on. I will render these songs as is and save them in my sonic graveyard. The chances I can recycle some of these ideas is high, and I am at least honoring their creation. 

## Get it out there

There is a case for half-formed things. The longer you have to dwell on something, the less likely you are to release it. 

YouTube/SoundCloud/Medium/IG/Tiktok have all made it easy to get work out there quickly from the moment of creation. I think overall they have been good and have democratized art and who can make it. There is something good in releasing something that’s created in the spontaneous moment, but there is also something good in working on something and putting effort into it. I’m trying to aim for a happy medium where creating is not wholly agonizing, but is rewarding in itself.

In a sea of endless creativity, our value lies in how we participate in the conversation of creation and how we react to other’s work. You will grow faster if you attempt to dialogue with those who interact with your art. But you must not lose yourself in this conversation and only focus on what other people want. What makes you an artist is what *you* want. Be true to yourself. But get it out there. Brian Eno and others have noted that a work of art has no value unless other people have experienced it. 

You are on a journey as an artist. Oftentimes, you will stumble many times in finding your path. You must forgive your stumbles and celebrate your wins, no matter how small they are. Otherwise, the stumbles will loom large in your brain and you will be stuck. Make room for your wins in your brain. 

