# On Late Bloomers

I am a late bloomer. It takes me a long time to figure things out creatively. My creative process almost never starts with a vision of what I want the work to be. I muddle my way through my creative process before I actually know what the work is about. I am not a visionary - I am a revisionary.  

[Malcolm Gladwell's essay](http://www.newyorker.com/magazine/2008/10/20/late-bloomers-2) suggests that early bloomer and late bloomer artists really do have distinct approaches to art. Early bloomers are conceptualists, whose idea of the work comes as a full formed vision, and creating the art is simply a matter of executing that vision. Prominent examples of conceptualists are Picasso and Orson Welles, whose best known works were executed in their youth (Welles directed "Citizen Kane" at the tender age of 23).

In contrast, late bloomers have an experimental approach, where each work of art is part of a continual process of exploration and improvement. When I work on a piece, it is often a long time from when I start a piece to the point where I understand the true form it will take. There are many artistic dead ends I must explore before I find the organic solution and path. Rarely is my artistic process a linear one. I am continually frustrated with myself and my abilities. But I have gradually gotten better, building on my past experiences and I am not a one trick pony.

I think that the work of late bloomers often seems truer to life because it has this messy process behind it. It reflects life because it has been shaped by the vagaries of life, by the daily joys and the daily tragedies. In contrast, the work of EBs is monolithic and rarely shaped by their circumstances, unless they are financial ones. Often, late bloomers' work feels less artificial than early bloomers' work.

In his essay "Confessions of a late bloomer," Scott Kauffman outlines some essential qualities for late bloomer success. Chiefly resilence, passion and perserverance - grit and failure tolerance are what's needed for late bloomer success. What late bloomers need is an environment and support to tolerate their brave failures - such support structures are lacking in this day and age. The narrative of a late bloomer's life, unless they are lucky to have rich parents, inevitably includes a tiring and soul sucking day job. Given such odds, is it surprising that so few late bloomers survive?

Survival as a late bloomer is a far greater accomplishment than anything an early bloomer has accomplished. It requires a large degree of resilience and internal drive and acceptance of failure.

Given our fascination with early bloomers, we often forget that some of the best artistic work is due to late bloomers who bring their life experience to the work. There are countless artists whose best work came later in their lives, from Cezanne, to Proust, to Trollope - each of these artists initially seemed failures, but slowly found their voice, through tireless work and experimentation.

I am not in favor of one or the other. The world needs both types, but we forget this whenever we think a young prodigy is more marketable than the artist who has years of blood and sweat behind his work. The truth behind what seems effortless is that it requires a lot of revisions to make it seem inevitable and effortless.

To the other late bloomers out there: it is worth enduring for your art. But you have to start somewhere and be willing to throw things away. Things you've toiled long and hard on. Others will probably not understand these pieces. That's okay - hopefully you learned something putting it together. That will have to do.

## Resources

* The book [Range: How Generalists Triumph in a Specialists' World](https://davidepstein.com/the-range/) is full of a lot of stories of Late Bloomers and how the range of their experiences made them stronger at their work.
* The [Malcolm Gladwell essay on Late Bloomers](http://www.newyorker.com/magazine/2008/10/20/late-bloomers-2) is well worth a read.
* I started learning Cello at 30, and one of the reasons was the [Cellists by Night](http://cellofun.yuku.com/forums/2/Cellists-by-Night-Forum) discussion board. I don't really read it any more (thanks to some overly pedantic posters), but there are lots of such discussion boards out there for late starters.
