# On internal standards

I have already talked about building your own personal aesthetic, but I haven't yet talked about having standards for when you decide a piece is finished or ready to go out into the world. 

The truth is that if you do not define your internal standards by which you judge your work successful, the world will destroy you. Relying on external validation may seem great when you have it, but the tastes of the public changes.  What once seemed so appealing about your work may no longer be appealing a year from now. External opinions are ultimately fleeting.

Ira Glass has noted that [the gap between execution and your own personal taste](https://www.brainpickings.org/2014/01/29/ira-glass-success-daniel-sax/) is often the hardest part of starting out as an artist. I  find this to be true from bitter experience.  We all agonize whether a work is finished or not. Honestly, a work is probably never finished, just abandoned, as goes the old quote. If you are perfectionist, then it will take you a long time to abandon it. But as Ira Glass notes, the more important thing is to just do a lot of work rather than obsess over perfecting each one.

In terms of standards, I believe that perfectionism is largely wasted in a world that only gives art a five-second once over before moving on. The question I always ask myself when I ask whether a work is finished is: *Does the work communicate what I want it to, or is the execution getting in the way?* I'm sure we all know artists who have brilliant ideas, but their execution is lacking. Without proper execution, art feels half-assed. Your friends may say they like it, but maybe they're just being nice. Everything needs to be edited down, pared down, to some extent to expose the strengths of the work. 

In terms of execution, there is ultimately a balance that must be struck between precision and passion in every art piece. Clarity and vagueness is another related spectrum. Some of the best pieces of art contain unsolvable mysteries at their center, but these mysteries are always wrapped in substance.  

As I've gotten older, I have gotten less anxious about letting my music out into the world. As I've said, opinions are really fleeting, so if I get a bad review I'm much less likely to take it personally. The reviewer rarely has knowledge that I do not about the art. I do my best, and I release music I believe in, and the rest is up to fate.

In the words of Brian Eno: "My feeling is that a work has little value until you “release” it, until you liberate it from yourself and your excuses for it — “It’s not quite finished yet,” ”The mix will make all the difference,” etc. Until you see it out there in the world along with everything else, you don’t really know what it is or what to think of it, so it’s of no use to you."

## Resources

[This interview of Brian Eno by David Mitchell is really great.](http://www.salon.com/2011/10/01/david_mitchell_brian_eno/)
