# On Failure

I recently had one of the worst gear failures of my career. My looper, the heart of my performance setup, failed catastrophically just as I was about to start my performance. No matter what I tried, the software betrayed me and didn't work. Luckily, some of my other equipment still worked. And I managed to not only perform, but do some of the best improvisation of my career. Not able to loop my cello playing (which I think of as improvising vertically), I had to improvise horizontally, repeating short sections, alternating with other melodies until it felt I had a song. And people seemed to like it, or at least didn't much care that it wasn't what they expected. The experience overall was tremendously freeing. I realized that I could handle the chaos that life threw at me and make it into art.

After this experience, it occurred to me that if you don't take failure personally, it does interesting things to you. If you accept failure as a circumstance, you may find that you work around failure in interesting ways. In the words of Samuel Beckett: "Try again. Fail again. Fail better."

Here are some of my selected thoughts on failure.

## Collaborate with Failure

As an improviser, I encourage you to collaborate with your failures. Looking at failures in the moment as an external circumstance will enable you to "use the disadvantage". Having a background in improvisation allows me to take a ["Yes, and..."](https://en.m.wikipedia.org/wiki/%22Yes,_And%22_rule) approach to shit as it happens and blows up. I look at it as collaborating with my circumstances.

What I mean is: the audience is forgiving. Take a chance. I long ago decided that a good performance has a chance of failure. I decided that failing in an interesting way was much more important to giving a glossy, perfected performance.  It's important to ride the edge of chaos when you perform. Otherwise, you are pretty much a human CD. Over-rehearsing feels way too safe. Riding on the edge of failure makes it much more exciting and engaging for you and the audience.

The most important part of performance is vulnerability. It's also the hardest for us as performers, since we are baring ourselves to possible ridicule. But vulnerability is also how we connect with our audience. Being vulnerable makes us seem human and gives the audience something to connect with.

> "Many times, the problem for young players is not that they’re not great.
> It’s that they’re afraid to go to these places, to take themselves
> emotionally to places that may be embarrassing, that may involve
> some sort of personal failure. It’s one thing to say, “It’s happy music.
> Then I’m going to use more vibrato or something.” No. The first step
> is to be able to take yourself to that place. And the hardest thing is
> that you have to do that over and over and over."
> - Geoff Nuttall, St. Lawrence String Quartet

## Make your failures interesting - go for fiasco

> Mistakes are not just opportunities for learning; they are, in an important sense,
> the only opportunity for learning or making something truly new. - Daniel Dennett

> Don’t search for the answers, which could not be given to you now, because you
> would not be able to live them. And the point is to live everything. Live the questions now. - Rilke

I think it's important is that you should be pushing yourself when you make art.  You need to push yourself in order to avoid repeating yourself. You should be striving for an artistic fiasco. Taking such risks makes art into a high-risk/high-reward venture. The critics may not take kindly to your (temporary) insanity, but that's just one point of view. Touching and moving people with your art requires taking risks and that is worth braving a few failures for. However, there has to be a reason for your risk beyond mere provocation. Provoking the audience only works one or two times in an artist's career before the audience realizes the artist is crying wolf.

It is also important to not become complacent with your work. Strive to learn new things and gain new experiences everyday. These experiences don't have to be big ones, but they should push your boundaries. Be bad at something. Let your inexperience and failure in these new experiences humble and recenter you. Realize that failure is not the end of the world.

## Don't take failure personally - avoid rumination

I have to emphasize that you shouldn't be taking failure personally. Many circumstances contributing to a failure are beyond your control: perhaps your work doesn't capture the gestalt, or it was released at the wrong time. Actors face rejection all the time when going for auditions, and it is bruising. As artists and performers, we often subject ourselves to the crushing weight of expectations. Paraphrasing the piano teacher Seymour Bernstein, many great artists/performers are assholes because they can achieve perfection in the world of performance but then have to deal with the fact that the world is not so perfect. Their expectations don't align with the true reality of the world.

Managing failure is really about managing your expectations. I believe that much of what we term as writer's block is such a fear of failure and unrealistic expectations of our work. To quote Sarah Lewis, "[Failure is an orphan until we give it a narrative.](https://www.goodreads.com/book/show/18143786-the-rise)" I understand that when we are young, we believe that our art can change the world. However, I think that the best we can strive for as we grow as artists is to cultivate gratitude for those who are receptive to our art, and to not feel entitled to a "wide audience". Honestly, I feel such an audience does not really exist any more.

It is also important not to endlessly obsess about your failure and what you could have done differently. Ruminating about failure leads to depression, which can lead to abandoning your art. Instead of admonishing yourself and beating yourself up, try reframing it as a new challenge. Instead of "That was awful, no one liked it. I'm not a good artist", you should be telling yourself, "well, that didn't work. What if I tried this instead?"

If done right, an artistic career is full of failures. The successes are few and far between, but are that much more sweeter for that reason. But these failures are opportunities to learn, not to beat yourself up. Beating yourself up will only make you risk-averse, and make your art too safe.

## Endure failure and grow from it

So your work was panned. Critics did not get the meaning of your work. Or even worse, your work, which you put years of work and your heart and soul into, was received by the world with a resounding meh. For most artists who don't live the charmed life of being in the spotlight, failure is a more common state than success. Or is it really failure? I believe that getting a work to the point at which it is released is a monumental accomplishment. Acknowledge the fact that you put effort into the work. Feel secure that you did everything you could under to do your best work under the circumstances.

Get this into your head. There is nothing wrong with you because your work did not make a big splash. There was usually a cultural   mismatch - it came out at the wrong time, or there was a work with more hype that overshadowed it. The initial response to a work of art is misleading. Your work may yet find an audience over a period of time.

## Our connections will sustain us

I have written before about the importance of building an artistic community. Part of failing well is to fail safely by building a community where you are supported. When you fail, it is these connections that will sustain you through your failures to try again. If you have been supportive of others, now is the time that they will give back to you. But sometimes you will have to ask for that support.

I am a big believer in the community created by art. The value of an artistic piece in my opinion is how much it inspires others to do art, not the monetary value. 

## Resources

* Sarah Lewis' [The Rise: Creativity, the Gift of Failure, and the Search for Mastery](https://www.goodreads.com/book/show/18143786-the-rise) is worth reading.
*  The NEA's issue on [Art and Failure](https://www.arts.gov/sites/default/files/nea_arts/NEA%20Arts_2014_no4_web.pdf) is a wonderful compilation of artists of all types talking about the role failure has played in their careers.