# On Self Doubt

I think that every artist has periods of self-doubt. Despite releasing multiple albums, despite having composed music for nearly twenty years, there are still the demons of self doubt in my head. I can still often be *the boy who takes everything personally*.

My most recent round of self doubt started with dissatisfaction with my cello tone. Although ultimately I'm an amateur cellist, it's hard not to compare my sound with more professional musicians. Why is it not as rich and varied?  It must be something to do with me. I’m just not good enough, I tell myself.

I have written before about how it’s [counterproductive to compare yourself to others](on-success-or-how-to-suck-it-up-and-be-happy-for-your-successful-friends.html), but I can’t help it sometimes. When I’m in this state, listening to other people's music is painful to me - each note can feel like a rebuke, and I can't be happy for my friends' accomplishments. It’s a bad place to be.

The worst of it is when external opinions sync with one's own self-critical voice. If there’s a review that [calls my playing "too swooningly romantic"](https://www.fluid-radio.co.uk/2017/07/marcus-fischer-film-variations/), I take it as validation of my own negative voice. I am so used to minimizing myself, wanting to disappear when that happens. I sometimes feel like I'm an albatross around the neck of my collaborators. So I disappear, stop connecting with people, stop going to shows. And I’m left struggling in the morass of self doubt.

What is the way back? For me, I think it has to do with three things: 1) reconnect with the people who value my work, 2) be more self compassionate, and 3) remember that I do art not for the external validation, but because the journey and process is in itself rewarding. I need to re-embrace my strengths as an amateur cellist. I can be adventurous in ways that other cellists can't. I need to embrace the ugliness and simplicity of my performances. My cello playing can sound different, since I don’t play so that I can pay the rent and eat. I can experiment.

The self compassion is the hardest part, especially after a childhood built on extreme self criticism. It can be hard not to replay these old tapes. I need to find new, more positive ways of motivation. At the same time, I have to be less precious of my art. My albums are documents of what I was feeling and what I was obsessed with at the time.

Being an artist means taking part in traditions and customs established by one’s predecessors and peers. It’s important to take part in this creative dialogue, but you have to be careful that it doesn’t become a monologue, either from the tradition side or your side. To err on the side of tradition means minimizing one’s art; to err on out own side means missing opportunities to make connections with others.

I think that we forget that it takes a certain bravery to be an artist, especially in such an age of anonymous reviews and rapid, unconsidered responses. It is a brave act to take something that is personal to us, part of our own internal mythology,  and show it to the world with the hope that it connects with someone. How easy it is to feel shut down if there’s one naysayer - or even worse, if there is no response. In such times, we must look into ourselves and ask ourself the essential question: *why do I make art?* We must disabuse ourselves of any romantic notions and truly embrace the struggle and joy of making art.
