--- 
title: "An Artist's Survival Guide"
author: "Ted Laderas"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: 
biblio-style: apalike
link-citations: yes
always_allow_html: yes
description: "This is a series of essays I wrote about how to make art in a largely indifferent world."
---

```{r echo=FALSE}
library(metathis)

meta() %>%
  meta_description(
    "This is a series of essays I wrote about how to make art in a largely indifferent world."
  ) %>% 
  meta_name("github-repo" = "laderast/artists_survival_guide") %>% 
  meta_viewport() %>% 
  meta_social(
    title = "An Artist's Survival Guide",
    url = "https://laderast.github.io/artists_survival_guide",
    og_type = "book",
    og_author = c("Ted Laderas"),
    twitter_card_type = "summary",
    twitter_creator = "@tladeras"
  )

```


# Introduction

To make art in the world is difficult. Making art in an indifferent world, when you have a small audience, is even more difficult.

This book consists of essays written from 2015 to 2020 about how to continue to make art in an indifferent world. They were mostly previously published on my blog: [15 People](https://15people.net). Hopefully you will find these essays helpful as you continue on in your artistic journey.

## About Me

I am a [Musician](https://15people.net), a [Data scientist](https://laderast.github.io) and an [Educator](https://laderast.github.io/cv). I have a pretty unique view of making art. 

Why should you listen to me? I have been making music and art in some form for over 28 years. I don't consider myself to be wildly successful, but I have managed to continue making art in some form or other, and I consider that mildly successful.

I have a number of releases and music and more information is available here: https://15people.net/music/. 

## A Couple Notes

This guide is not meant to give you advice about how to be successful and how to make money as an artist. That boils down to two things: hustle and luck. There are lots of guides out there for that. This guide is about all of the other moments around living as an artist and keeping your community and creativity flowing in hard times.

Also note it is called *An* Artist's Survival Guide, not *The* Artist's Survival Guide. As you continue in your artistic career, you will need to develop your own strategies to survive and live.

## License

This book is licensed under a [Creative Commons Attribution-NonCommercial 4.0 International license](https://creativecommons.org/licenses/by-nc/4.0/). Please share freely, but please contact me if you want to reuse or republish it (Ted Laderas, tedladeras [at] gmail).
